### ISSUE TITLE
Demo Deployment Checklist (Pathfinder Dev)

### ISSUE THREAD

**Issue by countable** [bcgov/sbc-search#109]
We want to deploy an instance of sbc-search on pathfinder that integrates with CDEV database and the sbc-auth test environment.

 - [x] auth (JWT) integration on front-end (Aaron)
 - [x] auth (JWT) decorators on back-end (Shirley)
 - [x] allocate a "dev" domain, like `sbc-search-dev.gov.bc.ca` or something. (Andrew)
 - [x] Run our buildconfig and deploymentconfig to create a deployment on pathfinder. (Shirley)
 - [x] Change the DB connection to use the CDEV database, using the IP, not DNS (Shirley)
 - [x] make any other parameters changes necessary. (Shirley)
 - [x] include changes from latest usability test where time permits (Aaron)
 - [x] get test credentails for using director search (Sumesh)
 - [x] tell countable what JWT claims to check (Sumesh)
