### ISSUE TITLE
Production Deployment Checklist

### ISSUE THREAD

**Issue by countable** [bcgov/sbc-search#120]
This is a necessary (not sufficient) checklist for release.

 - [ ] Create a DeploymentConfig with production parameters.
 - [ ] Switch to production auth service (is it released)
 - [ ] Check in with Patrick for other items.
