### ISSUE TITLE
search filters checklist post usability testing

### ISSUE THREAD

**Issue by countable** [bcgov/sbc-search#78]
- [x] remove simple search
- [x] add first name and last name filters by default
- [x] keep all filters editable all the time
- [x] add wildcard option in match type
- [x] add instruction copy
- [x] remove hero banner
- [x] default to AND instead of OR

**Comment by byshine** [comment]
I can get started on some of these

**Comment by jvanoyen** [comment]
All UI changes made:

Changes to General Layout/Search Inputs:
- remove hero banner/card layout (except for printable section of details page), change title text size
- added "Search Tips" dropdown
- changed page background colour to #F1F3F6
- changed search inputs and dropdowns
- "+ Add Filter" button now adds another row of empty inputs that say "(Select)" in grey
- filters remain editable inputs
- default to AND in dropdown next to search button


Search Results Page:

- Filing # greyed out and moved to leftmost column
- "Filing Address" column name changed to "Address"
- No more blue or underlined link text in the table, since the entire row (highlighted in grey) links to the details page
